package com.healthlog.demo.dto.feedback;

public enum FeedbackType {
	WEIGHT_NO_RECORD,
	WEIGHT_BIG_CHANGE,
	WEIGHT_SUDDEN_CHANGE,
	WEIGHT_GOAL_ACHIEVED,
	WEIGHT_RESUMED,

	SLEEP_NO_RECORD,
	SLEEP_NO_GOAL,
	SLEEP_SHORT,
	SLEEP_GOOD,
	SLEEP_CONTINUOUS_SHORT,
	SLEEP_RESUMED,

	WATER_NO_RECORD,
	WATER_NO_GOAL,
	WATER_LOW,
	WATER_ALMOST,
	WATER_COMPLETE,
	WATER_EXCESS,
	WATER_RESUMED,

	STEP_NO_RECORD,
	STEP_NO_GOAL,
	STEP_LOW,
	STEP_ALMOST,
	STEP_COMPLETE,
	STEP_RESUMED,
	STEP_SUDDEN_CHANGE,

	DAILY_COMPLETE,
	CONTINUOUS_RECORD,

	HEALTH_STREAK
}
